### ISSUE TITLE
Dimensions error

### ISSUE THREAD

**Issue by fabrizioreisluciani** [fsmMLK/inkscapeDimensions#1]
Hi,

I installed most of your extensions and they all work but Dimensions, it shows this error when previewing or applying:

```
Traceback (most recent call last):
  File "dimensions.py", line 832, in <module>
    dimension.affect()
  File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
    self.effect()
  File "dimensions.py", line 193, in effect
    [P1,P2] = self.getPointsLinDim(element,so.LINdirection)
  File "dimensions.py", line 784, in getPointsLinDim
    [P1,P2] = self.getPoints(element)
ValueError: too many values to unpack
```

Windows 7 Pro 64 bits, Python 2.7.15, all packages installed according to your instructions, InkscapeMadeEasy seems to be working since the other extensions work.

**Comment by pgilfernandez** [comment]
I also got a similar error, have you tried to select just a line with two vertexes in order to create a linear dimension?

**Comment by fabrizioreisluciani** [comment]
Interesting... I did what you suggested and it worked... it works for single lines...

**Comment by pgilfernandez** [comment]
Actually, this is the way to use it, it's documented but hard to read it, hehehe.
Anyway, for me it shifts the dimension so it doesn't work perfect...

**Comment by fabrizioreisluciani** [comment]
Thanks for your help, I'll use lines as placeholders then, it is no ideal but works all the same... more or less, but hey, we can't always have everything, right? It is a nice extension, by all means.

**Comment by fsmMLK** [comment]
Yes, in order to create linear dimension inications you must create a line with two vertexes only. I just realized the documentation contained 3 broken links to images describing the usage. Please check again the USAGE section for further information.
Chears.

The issue with general polylines is that inkscape's API does not provide a way for me to identify which segment of a multi-vertex polyline the used clicked ir order to create the dimension anotation there.

Let me know whether the corrected usage section solves your issue.
